openapi: "3.0.0"
info:
  version: 1.0.0
  title:  github-api-demo
  license:
    name: MIT
servers:
  - url: http://localhost:8080/v1
paths:
  /pull_requests/{repoId}:
    get:
      summary: List all pull requests
      operationId: listPullRequests
      tags:
        - pull_requests
      parameters:
        - name: repositoryId
          in: path
          required: true
          description: The id of the github repository
          schema:
            type: string
      responses:
        '200':
          description: A 
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/PullRequests"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pull_requests/{repoId}/{pullRequestId}:
    get:
      summary: Info for a specific pull request
      operationId: getPullRequestById
      tags:
        - pull_requests
      parameters:
        - name: repositoryId
          in: path
          required: true
          description: The id of the github repository
          schema:
            type: string
        - name: pullRequestId
          in: path
          required: true
          description: The id of the pull request to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PullRequests"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    PullRequest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
        commit_count:
          type: integer
          format: int64
    PullRequests:
      type: array
      items:
        $ref: "#/components/schemas/PullRequest"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
